Fixes the problem with folders and files in the workdir permissions
DataBiosphere/toil pull request #3229
Opened 2020-09-18 13:42 UTC by mberacochea

Instead of using python tempfile to create files and dirs in the
work dir use regular files with uniq names. This allows those files
and folders to honor the system permissions and umask.

This will fix #2355

2020-09-18 17:09 UTC, DailyDreaming requested changes
Other than the comment below, this seems alright.  Thanks for submitting the fix!

2020-09-18 18:58 UTC, adamnovak commented
I snuck in and patched this. Let's see if it works.

2020-09-18 19:08 UTC, adamnovak commented
Adding in UUIDs might make all our filenames longer in the job store. We'll have to see if that turns out to be a debuggability problem.

2020-09-20 11:28 UTC, mberacochea commented on src/toil/jobStores/fileJobStore.py
> +        tempStatsFile = os.path.join(self._getArbitraryStatsDir, tempStatsFileName)
Ugh, silly mistake. Thanks for catching that one.

2020-09-21 08:22 UTC, mberacochea commented
@adamnovak OK, that make sense. I can re-write this and use the first 8 chars from the UUID but checking existing folders to avoid collisions.

2020-09-25 16:58 UTC, adamnovak commented
I don't think truncating to 8 characters is a good idea. We should leave the UUIDs as full UUIDs.

The `mktemp`-type functions do some fancy work to ensure that you actually get a filename that doesn't already exist, to prevent collisions. If we're only using 8 **completely random** hex characters, we only have 32 bits of entropy (vs. 128 bits or something with a full UUID), and [collisions start to become possible with physically-achievable numbers of files](https://stackoverflow.com/a/14210379/402891).

2020-09-25 18:11 UTC, mberacochea commented
> I don't think truncating to 8 characters is a good idea. We should leave the UUIDs as full UUIDs.
> 
> The `mktemp`-type functions do some fancy work to ensure that you actually get a filename that doesn't already exist, to prevent collisions. If we're only using 8 **completely random** hex characters, we only have 32 bits of entropy (vs. 128 bits or something with a full UUID), and [collisions start to become possible with physically-achievable numbers of files](https://stackoverflow.com/a/14210379/402891).

OK. I agree, I'll revert that commit.

2020-10-21 18:02 UTC, mberacochea commented
Done. :)

> > I don't think truncating to 8 characters is a good idea. We should leave the UUIDs as full UUIDs.
> > The `mktemp`-type functions do some fancy work to ensure that you actually get a filename that doesn't already exist, to prevent collisions. If we're only using 8 **completely random** hex characters, we only have 32 bits of entropy (vs. 128 bits or something with a full UUID), and [collisions start to become possible with physically-achievable numbers of files](https://stackoverflow.com/a/14210379/402891).
> 
> OK. I agree, I'll revert that commit.

Done :)

2020-10-23 18:16 UTC, adamnovak approved these changes
Looks like this should work.

2020-10-23 18:20 UTC, adamnovak commented
@DailyDreaming I'm going to declare your review addressed and merge this.

2020-10-23 18:21 UTC, merged