Add test for parallel file import on S3
DataBiosphere/toil pull request #3506
Opened 2021-03-24 18:12 UTC by w-gao

Adds a unittest for #2707.

## Changelog Entry
To be copied to the [draft changelog](https://github.com/DataBiosphere/toil/wiki/Draft-Changelog) by merger:

 * Add test for parallel file import on S3

## Reviewer Checklist

 * [ ] Make sure it is coming from `issues/XXXX-fix-the-thing` in the Toil repo, or from an external repo.
    * [ ] If it is coming from an external repo, make sure to pull it in for CI with:
        ```
        contrib/admin/test-pr otheruser theirbranchname issues/XXXX-fix-the-thing
        ```
    * [ ] If there is no associated issue, [create one](https://github.com/DataBiosphere/toil/issues/new).
* [ ] Read through the code changes. Make sure that it doesn't have:
    * [ ] Addition of trailing whitespace.
    * [ ] New variable or member names in `camelCase` that want to be in `snake_case`.
    * [ ] New functions without [type hints](https://docs.python.org/3/library/typing.html).
    * [ ] New functions or classes without informative docstrings.
    * [ ] Changes to semantics not reflected in the relevant docstrings.
    * [ ] New or changed command line options for Toil workflows that are not reflected in `docs/running/cliOptions.rst`
    * [ ] New features without tests.
* [ ] Comment on the lines of code where problems exist with a review comment. You can shift-click the line numbers in the diff to select multiple lines.
* [ ] Finish the review with an overall description of your opinion.

## Merger Checklist

* [ ] Make sure the PR passes tests.
* [ ] Make sure the PR has been reviewed **since its last modification**. If not, review it.
* [ ] Merge with the Github "Squash and merge" feature.
    * [ ] If there are multiple authors' commits, add [Co-authored-by](https://github.blog/2018-01-29-commit-together-with-co-authors/) to give credit to all contributing authors.
* [ ] Copy its recommended changelog entry to the [Draft Changelog](https://github.com/DataBiosphere/toil/wiki/Draft-Changelog).
* [ ] Append the issue number in parentheses to the changelog entry.

2021-03-24 19:58 UTC, adamnovak requested changes
This looks like it should work, but it does seem to need some cleanup.

2021-03-24 19:58 UTC, adamnovak commented on src/toil/test/jobStores/jobStoreTest.py
> +            multiprocessing.cpu_count(),  # maximum
We have a Toil-specific CPU counting method (`toil.lib.threading.cpu_count`) that understands Kubernetes pods and won't make as many threads as there are cores on the underlying host.

2021-03-24 19:58 UTC, adamnovak commented on src/toil/test/jobStores/jobStoreTest.py
> +                # startTime = timeit.default_timer()
If you aren't really using timeit you could cut this and the import.

2021-03-24 19:58 UTC, adamnovak commented on src/toil/test/jobStores/jobStoreTest.py
> +        testFiles = [other._prepareTestFile(store, size) for _ in range(numOfFiles)]
This should be `snake_case` now.

2021-03-24 19:58 UTC, adamnovak commented on src/toil/test/jobStores/jobStoreTest.py
> +        numOfFiles = 5
This wants to be `snake_case`.

2021-03-24 19:58 UTC, adamnovak commented on src/toil/test/jobStores/jobStoreTest.py
> +                    jobStoreFileID = future.result()
`snake_case`

2021-03-24 19:58 UTC, adamnovak commented on src/toil/test/jobStores/jobStoreTest.py
> +                        fileMD5 = hashlib.md5(f.read()).hexdigest()
`snake_case`

2021-03-24 20:00 UTC, adamnovak commented
I think the Gitlab tests might have only failed for Kubernetes being full and unable to run stuff for us promptly.

2021-03-25 01:13 UTC, DailyDreaming reviewed
Overall, looks good to me.  See minor comments.

2021-03-25 01:13 UTC, DailyDreaming commented on src/toil/test/jobStores/jobStoreTest.py
> +        file_name = 'testfile_%s' % uuid.uuid4()
I appreciate the value-added snake case.

2021-03-30 17:20 UTC, adamnovak commented
@w-gao Is this PR ready to not be a draft anymore?

2021-03-30 18:42 UTC, w-gao commented
@adamnovak I think so, though I still have to update the type hints so diff_mypy can pass.

2021-03-31 01:04 UTC, DailyDreaming approved these changes
@w-gao Typing is pretty important for working code, but I'm of the opinion that typing in pure test files is nice to have, but not critical.  I'm in favor of merging this if tests pass.

2021-03-31 16:38 UTC, adamnovak approved these changes

2021-04-02 01:16 UTC, DailyDreaming commented
Tests have passed, I'm thinking that this is good to merge.  Thank you @w-gao .

2021-04-02 01:16 UTC, merged