Redirect stderr to /dev/null of lsf conf queries
DataBiosphere/toil pull request #3751
Opened 2021-08-17 20:30 UTC by juanesarango

## Changelog Entry

### WDL
* LSF users don't get errors from `bparams` and `lsfadmin` printed in their logs anymore.

## Reviewer Checklist
This PR fixes this issue I created: https://github.com/DataBiosphere/toil/issues/3750 

I found the solution with the help of @ddomenico

2021-08-18 07:41 UTC, mr-c requested changes
Thank you for reporting your issue and providing a fix! We should not throw these messages away while in debug mode. I can make that change if that would be easier.

2021-08-18 07:41 UTC, mr-c commented on src/toil/batchSystems/lsfHelper.py
> +        output = subprocess.check_output(cmd, stderr=subprocess.DEVNULL).decode('utf-8')
It would be nice if in debug mode we didn't throw this away.

2021-08-18 21:03 UTC, juanesarango commented
Something like this works:
```python
try:
    output = subprocess.check_output(cmd, stderr=subprocess.STDOUT).decode('utf-8')
except subprocess.CalledProcessError as exc:
    logger.debug(exc.output.decode())
    return None
```
@mr-c Is this what you are suggesting?

2021-08-18 21:07 UTC, mr-c commented
> Something like this works:
> ```python
> try:
>     output = subprocess.check_output(cmd, stderr=subprocess.STDOUT).decode('utf-8')
> except subprocess.CalledProcessError as exc:
>     logger.debug(exc.output.decode())
>     return None
> ```
> @mr-c Is this what you are suggesting?
> 

Sure! Or use `logger.isEnablefFor(logging.DEBUG)` to toggle setting `stderr` one way or the other

2021-08-18 23:04 UTC, mr-c approved these changes

2021-08-24 15:04 UTC, adamnovak commented
OK, I've pulled this into `issues/3750-lsf-queries-to-devnull` for CI testing.

2021-08-25 14:44 UTC, merged