Prevent exception from being raised when modifying dir permissions for clean up.
DataBiosphere/toil pull request #3778
Opened 2021-09-10 20:07 UTC by DailyDreaming

We may have permission to delete the folder but not modify it.  Since we just want to delete the directory, ignore it if we can't chmod it, and it will error on deleting the dir if it actually can't.

## Changelog Entry
To be copied to the [draft changelog](https://github.com/DataBiosphere/toil/wiki/Draft-Changelog) by merger:

 * Prevent exception from being raised when modifying dir permissions for clean up.

## Reviewer Checklist

 * [ ] Make sure it is coming from `issues/XXXX-fix-the-thing` in the Toil repo, or from an external repo.
    * [ ] If it is coming from an external repo, make sure to pull it in for CI with:
        ```
        contrib/admin/test-pr otheruser theirbranchname issues/XXXX-fix-the-thing
        ```
    * [ ] If there is no associated issue, [create one](https://github.com/DataBiosphere/toil/issues/new).
* [ ] Read through the code changes. Make sure that it doesn't have:
    * [ ] Addition of trailing whitespace.
    * [ ] New variable or member names in `camelCase` that want to be in `snake_case`.
    * [ ] New functions without [type hints](https://docs.python.org/3/library/typing.html).
    * [ ] New functions or classes without informative docstrings.
    * [ ] Changes to semantics not reflected in the relevant docstrings.
    * [ ] New or changed command line options for Toil workflows that are not reflected in `docs/running/{cliOptions,cwl,wdl}.rst` 
    * [ ] New features without tests.
* [ ] Comment on the lines of code where problems exist with a review comment. You can shift-click the line numbers in the diff to select multiple lines.
* [ ] Finish the review with an overall description of your opinion.

## Merger Checklist

* [ ] Make sure the PR passes tests.
* [ ] Make sure the PR has been reviewed **since its last modification**. If not, review it.
* [ ] Merge with the Github "Squash and merge" feature.
    * [ ] If there are multiple authors' commits, add [Co-authored-by](https://github.blog/2018-01-29-commit-together-with-co-authors/) to give credit to all contributing authors.
* [ ] Copy its recommended changelog entry to the [Draft Changelog](https://github.com/DataBiosphere/toil/wiki/Draft-Changelog).
* [ ] Append the issue number in parentheses to the changelog entry.

2021-09-11 10:37 UTC, mr-c commented on src/toil/worker.py
> +                pass
Can there at least be a log entry?

2021-09-13 15:50 UTC, adamnovak requested changes
We still want to know when cleanup doesn't work, but you're right it probably shouldn't fail the workflow.

Now someone will complain that a bunch of ostensibly successful workflows filled their disk. But the root cause will be that they're running in a weird environment with a recalcitrant filesystem and they need to do manual cleanup anyway, and they wouldn't have been able to swap the filesystem if the workflows had failed to complain about it. So it is probably better this way.

2021-09-13 15:50 UTC, adamnovak commented on src/toil/worker.py
> +                pass
Yeah, @mr-c is right; this should `logger.error` a complaint.

2021-09-15 15:34 UTC, adamnovak approved these changes
I just went and added the log entry I wanted.

2021-09-15 15:35 UTC, mr-c approved these changes

2021-09-20 14:02 UTC, merged