Type cleanups
DataBiosphere/toil pull request #3930
Opened 2021-11-18 19:51 UTC by mr-c

make pydocstyle_report diff_pydocstyle_report

## Changelog Entry
To be copied to the [draft changelog](https://github.com/DataBiosphere/toil/wiki/Draft-Changelog) by merger:

 * Many type cleanups, cwltoil.py is now checked strictly
 
## Reviewer Checklist

 * [ ] Make sure it is coming from `issues/XXXX-fix-the-thing` in the Toil repo, or from an external repo.
    * [ ] If it is coming from an external repo, make sure to pull it in for CI with:
        ```
        contrib/admin/test-pr otheruser theirbranchname issues/XXXX-fix-the-thing
        ```
    * [ ] If there is no associated issue, [create one](https://github.com/DataBiosphere/toil/issues/new).
* [ ] Read through the code changes. Make sure that it doesn't have:
    * [ ] Addition of trailing whitespace.
    * [ ] New variable or member names in `camelCase` that want to be in `snake_case`.
    * [ ] New functions without [type hints](https://docs.python.org/3/library/typing.html).
    * [ ] New functions or classes without informative docstrings.
    * [ ] Changes to semantics not reflected in the relevant docstrings.
    * [ ] New or changed command line options for Toil workflows that are not reflected in `docs/running/{cliOptions,cwl,wdl}.rst` 
    * [ ] New features without tests.
* [ ] Comment on the lines of code where problems exist with a review comment. You can shift-click the line numbers in the diff to select multiple lines.
* [ ] Finish the review with an overall description of your opinion.

## Merger Checklist

* [ ] Make sure the PR passes tests.
* [ ] Make sure the PR has been reviewed **since its last modification**. If not, review it.
* [ ] Merge with the Github "Squash and merge" feature.
    * [ ] If there are multiple authors' commits, add [Co-authored-by](https://github.blog/2018-01-29-commit-together-with-co-authors/) to give credit to all contributing authors.
* [ ] Copy its recommended changelog entry to the [Draft Changelog](https://github.com/DataBiosphere/toil/wiki/Draft-Changelog).
* [ ] Append the issue number in parentheses to the changelog entry.

2021-11-18 20:11 UTC, mr-c commented on Makefile
> +	    python -m pytest --cov=toil --durations=0 --log-level DEBUG --log-cli-level INFO -r s $(tests)
Whoops, I'll remove this on the next commit

2021-11-18 20:50 UTC, DailyDreaming requested changes
@mr-c Thanks for doing this!  See comment below.

2021-11-18 20:50 UTC, DailyDreaming commented on Makefile
> +	TRAVIS=true \
We need `TOIL_OWNER_TAG="shared"` so that our AWS bot doesn't kill any AWS resources we create.

2021-11-18 21:51 UTC, mr-c commented on src/toil/test/docs/scriptsTest.py
> -
This was accidental, will restore

2021-11-21 07:26 UTC, DailyDreaming approved these changes
LGTM.  Thank you @mr-c .

2021-11-21 07:27 UTC, merged