Issues/3916 export all slurm
DataBiosphere/toil pull request #4237
Opened 2022-10-04 19:37 UTC by Hexotical

## Changelog Entry
To be copied to the [draft changelog](https://github.com/DataBiosphere/toil/wiki/Draft-Changelog) by merger:

Make --export-all the default for slurm arguments

## Reviewer Checklist

 * [ ] Make sure it is coming from `issues/XXXX-fix-the-thing` in the Toil repo, or from an external repo.
    * [ ] If it is coming from an external repo, make sure to pull it in for CI with:
        ```
        contrib/admin/test-pr otheruser theirbranchname issues/XXXX-fix-the-thing
        ```
    * [ ] If there is no associated issue, [create one](https://github.com/DataBiosphere/toil/issues/new).
* [ ] Read through the code changes. Make sure that it doesn't have:
    * [ ] Addition of trailing whitespace.
    * [ ] New variable or member names in `camelCase` that want to be in `snake_case`.
    * [ ] New functions without [type hints](https://docs.python.org/3/library/typing.html).
    * [ ] New functions or classes without informative docstrings.
    * [ ] Changes to semantics not reflected in the relevant docstrings.
    * [ ] New or changed command line options for Toil workflows that are not reflected in `docs/running/{cliOptions,cwl,wdl}.rst` 
    * [ ] New features without tests.
* [ ] Comment on the lines of code where problems exist with a review comment. You can shift-click the line numbers in the diff to select multiple lines.
* [ ] Finish the review with an overall description of your opinion.

## Merger Checklist

* [ ] Make sure the PR passes tests.
* [ ] Make sure the PR has been reviewed **since its last modification**. If not, review it.
* [ ] Merge with the Github "Squash and merge" feature.
    * [ ] If there are multiple authors' commits, add [Co-authored-by](https://github.blog/2018-01-29-commit-together-with-co-authors/) to give credit to all contributing authors.
* [ ] Copy its recommended changelog entry to the [Draft Changelog](https://github.com/DataBiosphere/toil/wiki/Draft-Changelog).
* [ ] Append the issue number in parentheses to the changelog entry.

2022-10-06 18:39 UTC, adamnovak commented
This would fix #3916.

2022-10-06 19:03 UTC, adamnovak requested changes
I don't think this will quite work as written. And I think the simple substring check to detect if the option is set already is too easy to trick.

2022-10-06 19:03 UTC, adamnovak commented on docs/appendices/environment_vars.rst
> +|                                  | By default, "--export=ALL" is set.                 |
This makes it sound like if `TOIL_SLURM_ARGS` is not set, it has the same effect as setting it to `--export=ALL`. In fact, `--export=all` is supposed to be set whether `TOIL_SLURM_ARGS` is set or not. So you should elaborate here and explain how if the `--export` or `--export-file` options are used here, they will override the default behavior of exporting all environment variables.

2022-10-06 19:03 UTC, adamnovak commented on src/toil/batchSystems/slurm.py
> +                if "--export" not in nativeConfig:
You might also want to change the checks above for `--mem` and `--cpus-per-task` that are just substring checks.

2022-11-08 21:12 UTC, adamnovak commented
@Hexotical Do you want to finish this PR?

2023-01-03 16:50 UTC, adamnovak approved these changes
This looks good except for the docs, which I think I have a fix for.

2023-01-03 16:50 UTC, adamnovak commented on docs/appendices/environment_vars.rst
> +|                                  | By default, "--export=ALL" is set.                 |
```suggestion
|                                  | If neither ``--export`` nor ``--export-file`` is   |
|                                  | in the argument list, ``--export=ALL`` will be     |
|                                  | provided.                                          |
```

2023-01-23 16:13 UTC, adamnovak commented
@thiagogenez We're hoping to merge this as soon as we can get it working, thanks for the help!

Really for this you would want to talk to @Hexotical and not me, though; it looks like we forgot to set the assignee on #3916 but we kind of gave the issue to him to do.

And yeah, `docker exec export` is never going to work, because `exec` starts a new process and `export` is a Bash builtin to set an environment variable for itself. AFAIK only the process itself can set an environment variable on a running process.

2023-01-25 18:16 UTC, merged

2023-01-26 09:56 UTC, thiagogenez commented
> @thiagogenez We're hoping to merge this as soon as we can get it working, thanks for the help!
> 
> Really for this you would want to talk to @Hexotical and not me, though; it looks like we forgot to set the assignee on #3916 but we kind of gave the issue to him to do.
> 
> And yeah, `docker exec export` is never going to work, because `exec` starts a new process and `export` is a Bash builtin to set an environment variable for itself. AFAIK only the process itself can set an environment variable on a running process.

Thank you @adamnovak for the message. Glad to help with this. I'm very interested to test Toil on Slurm using Cactus. 

Please @Hexotical count on me if you need a hand for testing etc.