CWL: fix false warning when `outputSource` contains only one `None` value
DataBiosphere/toil pull request #4300
Opened 2022-12-14 20:09 UTC by w-gao

Fix #3991 by adding a condition to check if the input is `SkipNull` in `ResolveSource::pick_value()`.

```cwl
# example from the issue
...
outputs:
  out1:
    type: File
    outputSource:
      - echo/echoOut
    pickValue: first_non_null
...
```

When the `outputSource` only has one element, we internally store it as a tuple instead of a list of tuples. This source could evaluate to null but our [`pick_value()` function](https://github.com/DataBiosphere/toil/blob/releases/5.7.x/src/toil/cwl/cwltoil.py#L370) would return early and not filter out the SkipNull. 

## Changelog Entry
To be copied to the [draft changelog](https://github.com/DataBiosphere/toil/wiki/Draft-Changelog) by merger:

- CWL: fix false warning when `outputSource` contains only one `None` value

## Reviewer Checklist

 * [ ] Make sure it is coming from `issues/XXXX-fix-the-thing` in the Toil repo, or from an external repo.
    * [ ] If it is coming from an external repo, make sure to pull it in for CI with:
        ```
        contrib/admin/test-pr otheruser theirbranchname issues/XXXX-fix-the-thing
        ```
    * [ ] If there is no associated issue, [create one](https://github.com/DataBiosphere/toil/issues/new).
* [ ] Read through the code changes. Make sure that it doesn't have:
    * [ ] Addition of trailing whitespace.
    * [ ] New variable or member names in `camelCase` that want to be in `snake_case`.
    * [ ] New functions without [type hints](https://docs.python.org/3/library/typing.html).
    * [ ] New functions or classes without informative docstrings.
    * [ ] Changes to semantics not reflected in the relevant docstrings.
    * [ ] New or changed command line options for Toil workflows that are not reflected in `docs/running/{cliOptions,cwl,wdl}.rst` 
    * [ ] New features without tests.
* [ ] Comment on the lines of code where problems exist with a review comment. You can shift-click the line numbers in the diff to select multiple lines.
* [ ] Finish the review with an overall description of your opinion.

## Merger Checklist

* [ ] Make sure the PR passes tests.
* [ ] Make sure the PR has been reviewed **since its last modification**. If not, review it.
* [ ] Merge with the Github "Squash and merge" feature.
    * [ ] If there are multiple authors' commits, add [Co-authored-by](https://github.blog/2018-01-29-commit-together-with-co-authors/) to give credit to all contributing authors.
* [ ] Copy its recommended changelog entry to the [Draft Changelog](https://github.com/DataBiosphere/toil/wiki/Draft-Changelog).
* [ ] Append the issue number in parentheses to the changelog entry.

2022-12-14 21:04 UTC, mr-c requested changes
Thanks! Can you add a test case to confirm the fix?

2022-12-14 23:03 UTC, adamnovak approved these changes
Yeah a test would make this better. But are we set up to test for warnings? If that's not hard we should do it, but if testing for warnings turns out to be hard and there aren't already tests we can add on to for ResolveSource I'm not sure it makes sense to try and start with this.

2022-12-15 02:00 UTC, w-gao commented
I don't think we have existing tests for ResolveSource.

pytest does have a [caplog fixture](https://docs.pytest.org/en/7.1.x/reference/reference.html#std-fixture-caplog) and it seems to be straightforward to capture the logs and check if a log message is present in the output.

I added a small test that works well locally, so hopefully it passes on the CI as well.

2022-12-15 08:30 UTC, mr-c approved these changes

2022-12-15 08:31 UTC, merged