Implement a better config file system for CWL/WDL options
DataBiosphere/toil pull request #4666
Opened 2023-11-02 20:56 UTC by stxue1

This should resolve #4632 
## Changelog Entry
To be copied to the [draft changelog](https://github.com/DataBiosphere/toil/wiki/Draft-Changelog) by merger:

 * Updated docs for config file
 * Config file will include CWL and WDL arguments
   * Moved nonpositional CWL/WDL argument definitions to `common.py`
   * Config file will have all options be commented out when generated

## Reviewer Checklist

 * [ ] Make sure it is coming from `issues/XXXX-fix-the-thing` in the Toil repo, or from an external repo.
    * [ ] If it is coming from an external repo, make sure to pull it in for CI with:
        ```
        contrib/admin/test-pr otheruser theirbranchname issues/XXXX-fix-the-thing
        ```
    * [ ] If there is no associated issue, [create one](https://github.com/DataBiosphere/toil/issues/new).
* [ ] Read through the code changes. Make sure that it doesn't have:
    * [ ] Addition of trailing whitespace.
    * [ ] New variable or member names in `camelCase` that want to be in `snake_case`.
    * [ ] New functions without [type hints](https://docs.python.org/3/library/typing.html).
    * [ ] New functions or classes without informative docstrings.
    * [ ] Changes to semantics not reflected in the relevant docstrings.
    * [ ] New or changed command line options for Toil workflows that are not reflected in `docs/running/{cliOptions,cwl,wdl}.rst` 
    * [ ] New features without tests.
* [ ] Comment on the lines of code where problems exist with a review comment. You can shift-click the line numbers in the diff to select multiple lines.
* [ ] Finish the review with an overall description of your opinion.

## Merger Checklist

* [ ] Make sure the PR passes tests.
* [ ] Make sure the PR has been reviewed **since its last modification**. If not, review it.
* [ ] Merge with the Github "Squash and merge" feature.
    * [ ] If there are multiple authors' commits, add [Co-authored-by](https://github.blog/2018-01-29-commit-together-with-co-authors/) to give credit to all contributing authors.
* [ ] Copy its recommended changelog entry to the [Draft Changelog](https://github.com/DataBiosphere/toil/wiki/Draft-Changelog).
* [ ] Append the issue number in parentheses to the changelog entry.

2023-11-09 17:59 UTC, adamnovak requested changes
This looks pretty good. But some of the docs are worded oddly, and I think we need to not have the CWL and WDL front-ends talk about each other.

I also see some optional opportunities for condensing repeated logic.

2023-11-13 18:47 UTC, stxue1 commented
I combined a bunch of the duplicate code and moved all parser option related stuff into `src/toil/options`, where other files will now pull option related functions and values from. I'm not sure how easy it is to un-duplicate the CWL and WDL option code for suppressing though, and I can't think of a quick method off the top of my head, so I've left that alone for now.

2023-11-15 17:18 UTC, adamnovak approved these changes
The diff is a bit hard to read now since so much code moved and Git is aligning it wrong. But I think my complaints have been fixed!

2023-11-17 13:30 UTC, mr-c requested changes
`toil-cwl-runner --help` no longer lists all options

```
$ toil-cwl-runner --help
usage: toil-cwl-runner [-h]

options:
  -h, --help  show this help message and exit
```

<details><summary>Before this PR</summary>
```
usage: toil-cwl-runner [-h] [--logCritical] [--logError] [--logWarning]
                       [--logDebug] [--logInfo] [--logOff]
                       [--logLevel {Critical,Error,Warning,Debug,Info,critical,error,warning,debug,info,CRITICAL,ERROR,WARNING,DEBUG,INFO}]
                       [--logFile LOGFILE] [--rotatingLogging]
                       [--jobstore JOBSTORE] [--workDir WORKDIR]
                       [--coordinationDir COORDINATION_DIR] [--noStdOutErr]
                       [--stats] [--clean {always,onError,never,onSuccess}]
                       [--cleanWorkDir {always,onError,never,onSuccess}]
                       [--clusterStats [CLUSTERSTATS]] [--restart]
                       [--batchSystem {aws_batch,single_machine,grid_engine,lsf,mesos,slurm,torque,htcondor,kubernetes}]
                       [--disableHotDeployment]
                       [--disableAutoDeployment DISABLEAUTODEPLOYMENT]
                       [--maxJobs MAX_JOBS] [--maxLocalJobs MAX_LOCAL_JOBS]
                       [--manualMemArgs] [--runLocalJobsOnWorkers]
                       [--coalesceStatusCalls]
                       [--statePollingWait STATEPOLLINGWAIT]
                       [--batchLogsDir BATCH_LOGS_DIR]
                       [--awsBatchRegion AWS_BATCH_REGION]
                       [--awsBatchQueue AWS_BATCH_QUEUE]
                       [--awsBatchJobRoleArn AWS_BATCH_JOB_ROLE_ARN]
                       [--scale SCALE] [--dont_allocate_mem | --allocate_mem]
                       [--kubernetesHostPath KUBERNETES_HOST_PATH]
                       [--kubernetesOwner KUBERNETES_OWNER]
                       [--kubernetesServiceAccount KUBERNETES_SERVICE_ACCOUNT]
                       [--kubernetesPodTimeout KUBERNETES_POD_TIMEOUT]
                       [--symlinkImports SYMLINKIMPORTS]
                       [--moveOutputs MOVEOUTPUTS] [--caching CACHING]
                       [--provisioner {aws,gce,None}] [--nodeTypes NODETYPES]
                       [--maxNodes MAXNODES] [--minNodes MINNODES]
                       [--targetTime TARGETTIME] [--betaInertia BETAINERTIA]
                       [--scaleInterval SCALEINTERVAL]
                       [--preemptibleCompensation PREEMPTIBLECOMPENSATION]
                       [--nodeStorage NODESTORAGE]
                       [--nodeStorageOverrides NODESTORAGEOVERRIDES]
                       [--metrics METRICS]
                       [--assumeZeroOverhead ASSUME_ZERO_OVERHEAD]
                       [--defaultMemory DEFAULTMEMORY] [--defaultCores FLOAT]
                       [--defaultDisk INT]
                       [--defaultAccelerators ACCELERATOR[,ACCELERATOR...]]
                       [--defaultPreemptible [BOOL]] [--maxCores INT]
                       [--maxMemory INT] [--maxDisk INT]
                       [--retryCount RETRYCOUNT]
                       [--enableUnlimitedPreemptibleRetries ENABLEUNLIMITEDPREEMPTIBLERETRIES]
                       [--doubleMem DOUBLEMEM]
                       [--maxJobDuration MAXJOBDURATION]
                       [--rescueJobsFrequency RESCUEJOBSFREQUENCY]
                       [--maxLogFileSize MAXLOGFILESIZE]
                       [--writeLogs [WRITELOGS]]
                       [--writeLogsGzip [WRITELOGSGZIP]]
                       [--writeLogsFromAllJobs WRITELOGSFROMALLJOBS]
                       [--writeMessages WRITE_MESSAGES]
                       [--realTimeLogging REALTIMELOGGING]
                       [--disableChaining DISABLECHAINING]
                       [--disableJobStoreChecksumVerification DISABLEJOBSTORECHECKSUMVERIFICATION]
                       [--sseKey SSEKEY] [--setEnv NAME=VALUE or NAME]
                       [--servicePollingInterval SERVICEPOLLINGINTERVAL]
                       [--forceDockerAppliance FORCEDOCKERAPPLIANCE]
                       [--statusWait STATUSWAIT]
                       [--disableProgress DISABLEPROGRESS] [--config CONFIG]
                       [--debugWorker] [--disableWorkerOutputCapture]
                       [--badWorker BADWORKER]
                       [--badWorkerFailInterval BADWORKERFAILINTERVAL]
                       [--not-strict] [--enable-dev] [--enable-ext] [--quiet]
                       [--basedir BASEDIR] [--outdir OUTDIR] [--version]
                       [--log-dir LOG_DIR]
                       [--user-space-docker-cmd USER_SPACE_DOCKER_CMD | --singularity | --podman | --no-container | --leave-container]
                       [--custom-net CUSTOM_NET] [--cidfile-dir CIDFILE_DIR]
                       [--cidfile-prefix CIDFILE_PREFIX]
                       [--preserve-environment VAR1 VAR2 [VAR1 VAR2 ...]]
                       [--preserve-entire-environment]
                       [--destBucket DESTBUCKET]
                       [--beta-dependency-resolvers-configuration BETA_DEPENDENCY_RESOLVERS_CONFIGURATION]
                       [--beta-dependencies-directory BETA_DEPENDENCIES_DIRECTORY]
                       [--beta-use-biocontainers] [--beta-conda-dependencies]
                       [--tmpdir-prefix TMPDIR_PREFIX]
                       [--tmp-outdir-prefix TMP_OUTDIR_PREFIX]
                       [--force-docker-pull] [--no-match-user]
                       [--no-read-only] [--strict-memory-limit]
                       [--strict-cpu-limit] [--relax-path-checks]
                       [--default-container DEFAULT_CONTAINER]
                       [--compute-checksum | --no-compute-checksum]
                       [--eval-timeout EVAL_TIMEOUT] [--overrides OVERRIDES]
                       [--mpi-config-file MPI_CONFIG_FILE]
                       [--bypass-file-store] [--disable-streaming]
                       [--provenance PROVENANCE] [--enable-user-provenance]
                       [--disable-user-provenance] [--enable-host-provenance]
                       [--disable-host-provenance] [--orcid ORCID]
                       [--full-name CWL_FULL_NAME]
                       cwltool [cwljob ...]

positional arguments:
  cwltool               CWL file to run.
  cwljob                Input file or CWL options. If CWL workflow takes an
                        input, the name of the input can be used as an option.
                        For example: "toil-cwl-runner workflow.cwl --file1
                        file". If an input has the same name as a Toil option,
                        pass '--' before it.

options:
  -h, --help            show this help message and exit
  --not-strict
  --enable-dev          Enable loading and running development versions of CWL
  --enable-ext          Enable loading and running 'cwltool:' extensions to
                        the CWL standards.
  --quiet
  --basedir BASEDIR
  --outdir OUTDIR
  --version             show program's version number and exit
  --log-dir LOG_DIR     Log your tools stdout/stderr to this location outside
                        of container
  --user-space-docker-cmd USER_SPACE_DOCKER_CMD
                        (Linux/OS X only) Specify a user space docker command
                        (like udocker or dx-docker) that will be used to call
                        'pull' and 'run'
  --singularity         Use Singularity runtime for running containers.
                        Requires Singularity v2.6.1+ and Linux with kernel
                        version v3.18+ or with overlayfs support backported.
  --podman              Use Podman runtime for running containers.
  --no-container        Do not execute jobs in a Docker container, even when
                        `DockerRequirement` is specified under `hints`.
  --leave-container     Do not delete Docker container used by jobs after they
                        exit
  --preserve-environment VAR1 VAR2 [V [...]

2023-12-05 10:09 UTC, mr-c requested changes
From a diff of the old and new options

1. `--version` no longer has a description (was "show program's version number and exit")
2. `--custom-net` is now listed as being part of `extra_dockergroup` (that should probably not be printed)

From a diff of toil 5.12

3. `--runCwlInternalJobsOnWorkers` is missing from the summary section
4. ` [--linkImports | --noLinkImports]` is missing
5. `[--moveExports | --noMoveExports]` is missing
6. `--disableCaching` is missing

The [metavar](https://docs.python.org/3/library/argparse.html#metavar)s don't seem to be very helpful except to say that a particular command line option requires a value. Example: `--disableAutoDeployment DISABLEAUTODEPLOYMENT` ; wouldn't it be better to say `--disableAutoDeployment BOOLEAN` or similar? Likewise `--config PATH` instead of `--config CONFIG`, etc..

I appreciate that the environment variables are listed directly, thank you!

2023-12-07 18:02 UTC, mr-c commented on src/toil/options/common.py
> +    job_options.add_argument("--doubleMem", dest="doubleMem", type=convert_bool, default=False, metavar="bool",
```suggestion
    job_options.add_argument("--doubleMem", dest="doubleMem", type=convert_bool, default=False, metavar="BOOL",
```
 for consistency?

2023-12-07 18:02 UTC, mr-c approved these changes

2023-12-12 19:54 UTC, merged