Change default Singularity cache paths to be global
DataBiosphere/toil pull request #4762
Opened 2024-01-22 16:26 UTC by stxue1

This resolves #4761
This sets the default singularity cache paths to the same defaults as Singularity and MiniWDL. When creating a cluster, the cache paths are set to be under `/var/lib/toil` instead.
This also adds some config setters for the overrides to ensure they have the highest priority.

## Changelog Entry
To be copied to the [draft changelog](https://github.com/DataBiosphere/toil/wiki/Draft-Changelog) by merger:

 * Set default cache folders to be accessible between toil-wdl-runner workflows (Same as MiniWDL/Singularity defaults)
   * Set toil-wdl-runner cache folders on Toil managed clusters to be at `/var/lib/toil`

## Reviewer Checklist

 * [ ] Make sure it is coming from `issues/XXXX-fix-the-thing` in the Toil repo, or from an external repo.
    * [ ] If it is coming from an external repo, make sure to pull it in for CI with:
        ```
        contrib/admin/test-pr otheruser theirbranchname issues/XXXX-fix-the-thing
        ```
    * [ ] If there is no associated issue, [create one](https://github.com/DataBiosphere/toil/issues/new).
* [ ] Read through the code changes. Make sure that it doesn't have:
    * [ ] Addition of trailing whitespace.
    * [ ] New variable or member names in `camelCase` that want to be in `snake_case`.
    * [ ] New functions without [type hints](https://docs.python.org/3/library/typing.html).
    * [ ] New functions or classes without informative docstrings.
    * [ ] Changes to semantics not reflected in the relevant docstrings.
    * [ ] New or changed command line options for Toil workflows that are not reflected in `docs/running/{cliOptions,cwl,wdl}.rst` 
    * [ ] New features without tests.
* [ ] Comment on the lines of code where problems exist with a review comment. You can shift-click the line numbers in the diff to select multiple lines.
* [ ] Finish the review with an overall description of your opinion.

## Merger Checklist

* [ ] Make sure the PR passes tests.
* [ ] Make sure the PR has been reviewed **since its last modification**. If not, review it.
* [ ] Merge with the Github "Squash and merge" feature.
    * [ ] If there are multiple authors' commits, add [Co-authored-by](https://github.blog/2018-01-29-commit-together-with-co-authors/) to give credit to all contributing authors.
* [ ] Copy its recommended changelog entry to the [Draft Changelog](https://github.com/DataBiosphere/toil/wiki/Draft-Changelog).
* [ ] Append the issue number in parentheses to the changelog entry.

2024-01-22 16:59 UTC, adamnovak requested changes
This looks like it should work, but I think it needs some documentation improvements. We want it to be easy for the user to figure out that:

1. If they are running `toil-wdl-runner` (or I guess `toil-cwl-runner` in Singularity mode?) on a Toil-managed Kubernetes cluster, all the environment varialbes and stuff are our job and it should Just Work and already be efficient.
2. If they are using Singularity themselves on a Toil-managed Kubernetes cluster, Toil is setting things that Singularity will pick up on, and the user will have to actually think about cross-pod synchronization or provide their own per-job `SINGULARITY_CACHEDIR`.

2024-01-22 16:59 UTC, adamnovak commented on docs/running/cloud/kubernetes.rst
> +Note that Docker containers cannot be run inside of unprivileged Kubernetes pods (which are themselves containers). The Docker daemon does not (yet) support this. Other tools, such as Singularity in
We should note here that:
* `toil-wdl-runner` has batteries included and does all the necessary locking
* `TOIL_KUBERNETES_HOST_PATH` is set correctly by default on Toil-managed Kubernetes clusters so the user does not have to touch it.
* `SINGULARITY_CACHEDIR` is set to a shared location by default on Toil-managed Kubernetes clusters, so the user *will* need to either implement the appropriate locking there or set it somewhere else.

2024-01-22 16:59 UTC, adamnovak commented on src/toil/wdl/wdltoil.py
> +            miniwdl_cache = os.path.join(os.path.expanduser("~"), "/.cache/miniwdl")
This sounds like we're actually setting these, but actually these are default fallback values.

2024-01-22 16:59 UTC, adamnovak commented on src/toil/wdl/wdltoil.py
> +            miniwdl_cache = os.path.join(os.path.expanduser("~"), "/.cache/miniwdl")
We don't need the leading "/" on the paths we're joining on.

2024-01-22 16:59 UTC, adamnovak commented on docs/running/cloud/kubernetes.rst
> +Note that Docker containers cannot be run inside of unprivileged Kubernetes pods (which are themselves containers). The Docker daemon does not (yet) support this. Other tools, such as Singularity in
It might also be worth pointing people at the code Toil uses to do the locking, instead of saying it will be added to Toil in the future.

2024-01-22 17:01 UTC, mr-c commented
>     1. If they are running `toil-wdl-runner` (or I guess `toil-cwl-runner` in Singularity mode?) on a Toil-managed Kubernetes cluster, all the environment varialbes and stuff are our job and it should Just Work and already be efficient.

`toil-cwl-runner --singularity` doesn't use any of this code, AFAICT

2024-01-23 17:31 UTC, adamnovak commented
Then I guess we should note that too, and maybe open an issue for Toil to add synchronization to stop simultaneous Singularity pulls inside `cwltool`.

@mr-c Is there any probability that `cwltool` itself would implement its own logic to stop multiple simultaneous `cwltool` invocations, or multiple CommandLineTools in a workflow running at once, from trying to simultaneously `singularity pull` with the same Singularity cache directory?

2024-01-25 16:57 UTC, adamnovak requested changes
@stxue1 I think the content is about right now, but the formatting doesn't look like it's going to be right once `make docs` gets ahold of it.

2024-01-25 16:57 UTC, adamnovak commented on docs/running/cloud/kubernetes.rst
> +  On clusters created with the ``launch-cluster`` command, no setup is required. ``TOIL_KUBERNETES_HOST_PATH`` is already set to ``/var/lib/toil``. ``SINGULARITY_CACHEDIR`` is set to ``/var/lib/toil/
It looks like this comes out as a block quote in RST?
![Screenshot 2024-01-25 at 11 54 22](https://github.com/DataBiosphere/toil/assets/5062495/494a740b-5330-4428-a08f-bd103f61e748)

Maybe these should be underlined subheadings instead. Or just bolded introductory phrases.

2024-01-30 17:18 UTC, adamnovak approved these changes

2024-01-31 12:25 UTC, mr-c commented
> @mr-c Is there any probability that `cwltool` itself would implement its own logic to stop multiple simultaneous `cwltool` invocations, or multiple CommandLineTools in a workflow running at once, from trying to simultaneously `singularity pull` with the same Singularity cache directory?

I am open to it, but no one has volunteered to do such a thing yet

2024-02-02 13:35 UTC, merged