Add caching support for CWL
DataBiosphere/toil pull request #5187
Opened 2024-12-17 03:55 UTC by stxue1

Resolves #4298 

Adds support for the cwltool equivalent `--cachedir`. This should make toil-cwl-runner be cache aware and use previous steps when possible and properly restart when there are new. This is different than the `--restart` flag. Jobs *previously* ran with `--cachedir` can rerun with `--cachedir` and not with `--restart`. `--restart` should be used to run failed jobs that should succeed. If the CWL needs editing, then caching should be used, although this will take significantly more storage space compared to the default behavior. Ideally, this should only be used for development purposes.

## Changelog Entry
To be copied to the [draft changelog](https://github.com/DataBiosphere/toil/wiki/Draft-Changelog) by merger:

 * Add caching to `toil-cwl-runner`

## Reviewer Checklist

 * [ ] Make sure it is coming from `issues/XXXX-fix-the-thing` in the Toil repo, or from an external repo.
    * [ ] If it is coming from an external repo, make sure to pull it in for CI with:
        ```
        contrib/admin/test-pr otheruser theirbranchname issues/XXXX-fix-the-thing
        ```
    * [ ] If there is no associated issue, [create one](https://github.com/DataBiosphere/toil/issues/new).
* [ ] Read through the code changes. Make sure that it doesn't have:
    * [ ] Addition of trailing whitespace.
    * [ ] New variable or member names in `camelCase` that want to be in `snake_case`.
    * [ ] New functions without [type hints](https://docs.python.org/3/library/typing.html).
    * [ ] New functions or classes without informative docstrings.
    * [ ] Changes to semantics not reflected in the relevant docstrings.
    * [ ] New or changed command line options for Toil workflows that are not reflected in `docs/running/{cliOptions,cwl,wdl}.rst` 
    * [ ] New features without tests.
* [ ] Comment on the lines of code where problems exist with a review comment. You can shift-click the line numbers in the diff to select multiple lines.
* [ ] Finish the review with an overall description of your opinion.

## Merger Checklist

* [ ] Make sure the PR passed tests, including the Gitlab tests, for the most recent commit in its branch.
* [ ] Make sure the PR has been reviewed. If not, review it. If it has been reviewed and any requested changes seem to have been addressed, proceed.
* [ ] Merge with the Github "Squash and merge" feature.
    * [ ] If there are multiple authors' commits, add [Co-authored-by](https://github.blog/2018-01-29-commit-together-with-co-authors/) to give credit to all contributing authors.
* [ ] Copy its recommended changelog entry to the [Draft Changelog](https://github.com/DataBiosphere/toil/wiki/Draft-Changelog).
* [ ] Append the issue number in parentheses to the changelog entry.

2024-12-17 15:40 UTC, mr-c requested changes
Thank you for this @stxue1 !

I tested this PR using the CWL conformance tests; without `--cachedir` they still pass.

Alas, if I add  `--cachedir` then 134  of the conformance tests fail (though 242 test DO pass!)

2024-12-18 00:15 UTC, stxue1 commented
> Thank you for this @stxue1 !
> 
> I tested this PR using the CWL conformance tests; without `--cachedir` they still pass.
> 
> Alas, if I add `--cachedir` then 134 of the conformance tests fail (though 242 test DO pass!)

Thanks, I tested it on my machine and I think I tracked down the bug. I think it has to do with how we move around files from cwltool to Toil. We do some relocation of outputs from when we call cwltool internally which is messing some things up. It seems like setting a [cache directory](https://github.com/common-workflow-language/cwltool/blob/c6782ff11d345dcc86a79e1d582fbbaa8a61e8c1/cwltool/command_line_tool.py#L932) will set the [current working directory](https://github.com/common-workflow-language/cwltool/blob/c6782ff11d345dcc86a79e1d582fbbaa8a61e8c1/cwltool/job.py#L705) of the file to be [written to](https://github.com/common-workflow-language/cwltool/blob/c6782ff11d345dcc86a79e1d582fbbaa8a61e8c1/cwltool/job.py#L683).

When we execute the [Toil job's side](https://github.com/DataBiosphere/toil/blob/fe9a811254dab31b1f5e562d992127e1c71c9554/src/toil/cwl/cwltoil.py#L2849-L2854), I think we [set the destination directory](https://github.com/common-workflow-language/cwltool/blob/c6782ff11d345dcc86a79e1d582fbbaa8a61e8c1/cwltool/executors.py#L94-L96) as the jobstore, resulting in the outputs being [relocated](https://github.com/common-workflow-language/cwltool/blob/c6782ff11d345dcc86a79e1d582fbbaa8a61e8c1/cwltool/executors.py#L141) [eventually](https://github.com/common-workflow-language/cwltool/blob/c6782ff11d345dcc86a79e1d582fbbaa8a61e8c1/cwltool/process.py#L366) without [copying/symlinking](https://github.com/common-workflow-language/cwltool/blob/c6782ff11d345dcc86a79e1d582fbbaa8a61e8c1/cwltool/process.py#L339).

Since caching depends on cwltool behavior, it is probably best to either copy the files into the jobstore (or figure out a way for the jobstore to be cache aware?). I have yet to find an entrypoint to control the `relocateOutputs` behavior on the Toil side though.

2024-12-18 19:42 UTC, mr-c commented
>  I have yet to find an entrypoint to control the `relocateOutputs` behavior on the Toil side though.

We can add one on the cwltool side, if needed.

2024-12-18 22:27 UTC, stxue1 commented
> > I have yet to find an entrypoint to control the `relocateOutputs` behavior on the Toil side though.
> 
> We can add one on the cwltool side, if needed.

I believe I was able to find an entrypoint

2024-12-19 19:53 UTC, mr-c commented
> Alas, if I add `--cachedir` then 134 of the conformance tests fail (though 242 test DO pass!)

As of https://github.com/DataBiosphere/toil/pull/5187/commits/68f88e04e358aaf313a2c54377a00c6d815a7fe1, 128 tests fail.

2024-12-19 20:12 UTC, stxue1 commented
> > Alas, if I add `--cachedir` then 134 of the conformance tests fail (though 242 test DO pass!)
> 
> As of [68f88e0](https://github.com/DataBiosphere/toil/commit/68f88e04e358aaf313a2c54377a00c6d815a7fe1), 128 tests fail.

@mr-c Was this run with a clean cache directory? If the cache directory was populated with the previous broken version of toil-cwl-runner then the runner will look up files from previous cached runs, and they won't exist. I ran some of the tests on my machine and they seem okay so far. Also, how many tests in parallel were run? It might be possible it could be a synchronization issue.

2024-12-19 20:21 UTC, mr-c commented
> > > Alas, if I add `--cachedir` then 134 of the conformance tests fail (though 242 test DO pass!)
> > 
> > As of [68f88e0](https://github.com/DataBiosphere/toil/commit/68f88e04e358aaf313a2c54377a00c6d815a7fe1), 128 tests fail.
> 
> @mr-c Was this ran with a clean cache directory? If the cache directory was populated with the previous broken version of toil-cwl-runner then the runner will look up files from previous cached runs, and they won't exist. I ran some of the tests on my machine and they seem okay so far. Also, how many tests in parallel were run? It might be possible it could be a synchronization issue.

Clean directory, `-j8`. I can try without parallel, and l will confirm that cwltool can run with caching in parallel

2024-12-19 21:53 UTC, mr-c commented
> I ran some of the tests on my machine and they seem okay so far.

FYI: Here is my invocation run from the root of a checkout of https://github.com/common-workflow-language/cwl-v1.2

`./run_test.sh RUNNER=toil-cwl-runner EXTRA="--clean=always --relax-path-checks --podman --cachedir=/home/michael/cwl-v1.2/toil-cache"`

Running not in parallel, I still get 127 failures.

with `RUNNER=cwltool` I am able to run in parallel (with 6 failures, though I think they are specific to my development environment); And re-running using the previous cache directory repeats the outcome.

2024-12-20 20:30 UTC, stxue1 commented
> > I ran some of the tests on my machine and they seem okay so far.
> 
> FYI: Here is my invocation run from the root of a checkout of https://github.com/common-workflow-language/cwl-v1.2
> 
> `./run_test.sh RUNNER=toil-cwl-runner EXTRA="--clean=always --relax-path-checks --podman --cachedir=/home/michael/cwl-v1.2/toil-cache"`
> 
> Running not in parallel, I still get 127 failures.
> 
> with `RUNNER=cwltool` I am able to run in parallel (with 6 failures, though I think they are specific to my development environment); And re-running using the previous cache directory repeats the outcome.

Oddly enough, running the same command on my machine (but without `--podman`) only gives me 2 failing tests:
```
$ ./run_test.sh RUNNER=toil-cwl-runner EXTRA="--clean=always --relax-path-checks --cachedir=cache"
...

Test [232/378] cwl_requirements_override_static: Test conflicting requirements in input document via EnvVarRequirement
Test 232 failed: /home/heaucques/Documents/toil/venv3.12/bin/toil-cwl-runner --clean=always --relax-path-checks --cachedir=cache --outdir=/tmp/tmpzie43tg5 --quiet tests/env-tool3.cwl tests/env-job4.yaml
Test conflicting requirements in input document via EnvVarRequirement
Compare failure expected: {
    "out": {
        "checksum": "sha1$715e62184492851512a020c36ab7118eca114a59",
        "class": "File",
        "location": "out",
        "size": 23
    }
}
got: {
    "out": {
        "basename": "out",
        "checksum": "sha1$b3ec4ed1749c207e52b3a6d08c59f31d83bff519",
        "class": "File",
        "location": "file:///tmp/tmpzie43tg5/out",
        "nameext": "",
        "nameroot": "out",
        "path": "/tmp/tmpzie43tg5/out",
        "size": 15
    }
}
caused by: failed comparison for key 'out': expected: {
    "checksum": "sha1$715e62184492851512a020c36ab7118eca114a59",
    "class": "File",
    "location": "out",
    "size": 23
}
got: {
    "basename": "out",
    "checksum": "sha1$b3ec4ed1749c207e52b3a6d08c59f31d83bff519",
    "class": "File",
    "location": "file:///tmp/tmpzie43tg5/out",
    "nameext": "",
    "nameroot": "out",
    "path": "/tmp/tmpzie43tg5/out",
    "size": 15
}
caused by: Output file checksums do not match: actual 'sha1$b3ec4ed1749c207e52b3a6d08c59f31d83bff519' is not equal to expected 'sha1$715e62184492851512a020c36ab7118eca114a59'

...

Test [337/378] iwd-container-entryname3: Test input mount locations when container is a hint (should fail)
Test 337 failed: /home/heaucques/Documents/toil/venv3.12/bin/toil-cwl-runner --clean=always --relax-path-checks --cachedir=cache --outdir=/tmp/tmpfeo35a5x --quiet tests/iwd/iwd-container-entryname3.cwl tests/loadContents/input.yml
Test input mount locations when container is a hint (should fail)
Returned zero but it should be non-zero
```
I'll run it again with podman and see if anything changes.

2025-01-15 05:01 UTC, stxue1 commented
I think I accidentally left a local change to cwltool without realizing it and forgot to open the respective cwltool PR until later. I've opened the PR now and updated cwltool to the latest version with the update, ideally the conformance tests will pass now, but iirc there may be 2 tests that still fail.

2025-01-16 23:50 UTC, adamnovak approved these changes
This looks like it should work! Much simpler than the WDL version!

2025-01-17 15:52 UTC, mr-c submitted a review, later dismissed
Much improved; and thanks again for the fix sent to cwltool!

Two CWL v1.2 conformance tests fail locally for me when using a shared `--cachedir` (that was initially empty):

```
Test 232 failed: /home/michael/src/toil2/env3.12/bin/toil-cwl-runner --clean=always --relax-path-checks --podman --cachedir=/home/michael/cwl-v1.2/toil-cache --outdir=/tmp/tmpzyr_9q07 --quiet tests/env-tool3.cwl tests/env-job4.yaml
Test conflicting requirements in input document via EnvVarRequirement
Compare failure expected: {
    "out": {
        "checksum": "sha1$715e62184492851512a020c36ab7118eca114a59",
        "class": "File",
        "location": "out",
        "size": 23
    }
}
got: {
    "out": {
        "basename": "out",
        "checksum": "sha1$b3ec4ed1749c207e52b3a6d08c59f31d83bff519",
        "class": "File",
        "location": "file:///tmp/tmpzyr_9q07/out",
        "nameext": "",
        "nameroot": "out",
        "path": "/tmp/tmpzyr_9q07/out",
        "size": 15
    }
}
caused by: failed comparison for key 'out': expected: {
    "checksum": "sha1$715e62184492851512a020c36ab7118eca114a59",
    "class": "File",
    "location": "out",
    "size": 23
}
got: {
    "basename": "out",
    "checksum": "sha1$b3ec4ed1749c207e52b3a6d08c59f31d83bff519",
    "class": "File",
    "location": "file:///tmp/tmpzyr_9q07/out",
    "nameext": "",
    "nameroot": "out",
    "path": "/tmp/tmpzyr_9q07/out",
    "size": 15
}
caused by: Output file checksums do not match: actual 'sha1$b3ec4ed1749c207e52b3a6d08c59f31d83bff519' is not equal to expected 'sha1$715e62184492851512a020c36ab7118eca114a59'
```
I confirmed this manually, correct output is produced without `--cachedir`; incorrect output is "hello test env" instead of "conflict_user_override"

```
Test 337 failed: /home/michael/src/toil2/env3.12/bin/toil-cwl-runner --clean=always --relax-path-checks --podman --cachedir=/home/michael/cwl-v1.2/toil-cache --outdir=/tmp/tmptwczsgzv --quiet tests/iwd/iwd-container-entryname3.cwl tests/loadContents/input.yml
Test input mount locations when container is a hint (should fail)
Returned zero but it should be non-zero
```

I also confirmed this manually, this test correctly fails without `--cachedir`.

For completeness, I re-ran the conformance tests again; re-using the shared cache directory from the first run. The same tests above still fail; but 8 other tests also fail:

```
Test 229 failed: /home/michael/src/toil2/env3.12/bin/toil-cwl-runner --clean=always --relax-path-checks --podman --cachedir=/home/michael/cwl-v1.2/toil-cache --outdir=/tmp/tmppphahmca --quiet tests/stage-array-dirs.cwl tests/stage-array-dirs-job.yml
Test array of directories InitialWorkDirRequirement
Compare failure expected: {
    "output": [
        {
            "checksum": "sha1$da39a3ee5e6b4b0d3255bfef95601890afd80709",
            "class": "File",
            "location": "a",
            "size": 0
        },
        {
            "checksum": "sha1$da39a3ee5e6b4b0d3255bfef95601890afd80709",
            "class": "File",
            "location": "B",
            "size": 0
        }
    ]
}
got: {
    "output": []
}
caused by: failed comparison for key 'output': expected: [
    {
        "checksum": "sha1$da39a3ee5e6b4b0d3255bfef95601890afd80709",
        "class": "File",
        "location": "a",
        "size": 0
    },
    {
        "checksum": "sha1$da39a3ee5e6b4b0d3255bfef95601890afd80709",
        "class": "File",
        "location": "B",
        "size": 0
    }
]
got: []
caused by: lengths don't match
```

```
Test 253 failed: /home/michael/src/toil2/env3.12/bin/toil-cwl-runner --clean=always --relax-path-checks --podman --cachedir=/home/michael/cwl-v1.2/toil-cache --outdir=/tmp/tmpa9fmsg7e --quiet tests/exitcode.cwl tests/empty.json
Can access exit code in outputEval
Compare failure expected: {
    "code": 7
}
got: {
    "code": true
}
caused by: failed comparison for key 'code': expected: 7
got: true
```

```
Test 333 failed: /home/michael/src/toil2/env3.12/bin/toil-cwl-runner --clean=always --relax-path-checks --podman --cachedir=/home/michael/cwl-v1.2/toil-cache --outdir=/tmp/tmp7jdbyeai --quiet tests/iwd/iwd-fileobjs1.cwl
Test File and Directory object in listing
Returned non-zero
```

```
Test 334 failed: /home/michael/src/toil2/env3.12/bin/toil-cwl-runner --clean=always --relax-path-checks --podman --cachedir=/home/michael/cwl-v1.2/toil-cache --outdir=/tmp/tmpvii3c2sz --quiet tests/iwd/iwd-fileobjs2.cwl
Test File and Directory object in listing
Returned non-zero
```

```
Test 340 failed: /home/michael/src/toil2/env3.12/bin/toil-cwl-runner --clean=always --relax-path-checks --podman --cachedir=/home/michael/cwl-v1.2/toil-cache --outdir=/tmp/tmp8r91ctqm --quiet tests/iwd/iwd-subdir-wf.cwl tests/iwd/iwd-subdir-job.yml
Test emitting a subdirectory from initial workdir
Returned non-zero
```

```
Test 371 failed: /home/michael/src/toil2/env3.12/bin/toil-cwl-runner --clean=always --relax-path-checks --podman --cachedir=/home/michael/cwl-v1.2/toil-cache --outdir=/tmp/tmpjrsjkq5f --quiet tests/capture-files-and-dirs.cwl tests/dir-job.yml
Test that both files and directories are captured by glob evaluation when type is [Directory, File]
Compare failure expected: {
    "result": [
        {
            "basename": "a",
            "checksum": "sha1$da39a3ee5e6b4b0d3255bfef95601890afd80709",
            "class": "File",
            "size": 0
        },
        {
            "basename": "b",
            "checksum": "sha1$da39a3ee5e6b4b0d3255bfef95601890afd80709",
            "class": "File",
            "size": 0
        },
        {
            "basename": "c",
            "class": "Directory",
            "listing": [
                {
                    "basename": "d",
                    "checksum": "sha1$da39a3ee5e6b4b0d3255bfef95601890afd80709",
                    "class": "File",
                    "size": 0
                }
            ]
        }
    ]
}
got: {
    "result": []
}
caused by: failed comparison for key 'result': expected: [
    {
        "basename": "a",
        "checksum": "sha1$da39a3ee5e6b4b0d3255bfef95601890afd80709",
        "class": "File",
        "size": 0
    },
    {
        "basename": "b",
        "checksum": "sha1$da39a3ee5e6b4b0d3255bfef95601890afd80709",
        "class": "File",
        "size": 0
    },
    {
        "basename": "c",
        "class": "Directory",
        "listing": [
            {
                "basename": "d",
                "checksum": "sha1$da39a3ee5e6b4b0d3255bfef95601890afd80709",
                "class": "File",
                "size": 0
            }
        ]
    }
]
got: []
caused by: lengths don't match
```

2025-01-23 18:29 UTC, stxue1 commented
@mr-c 
I believe something similar is going on with the `iwd-container-entryname3` test. Something with Docker hint is not being used as part of the cache key in the lookup and a later test is able to find a previous run where it was a requirement and not a hint.
```
cwltest --tool cwltool -s=iwd-container-entryname1,iwd-container-entryname3 --test conformance_tests.yaml -- --cachedir cache
Test [335/378] iwd-container-entryname1: Test input mount locations when container required
Test [337/378] iwd-container-entryname3: Test input mount locations when container is a hint (should fail)
Test 337 failed: cwltool --cachedir cache --outdir=/tmp/tmpo9cj1782 --quiet tests/iwd/iwd-container-entryname3.cwl tests/loadContents/input.yml
Test input mount locations when container is a hint (should fail)
Returned zero but it should be non-zero
1 tests passed, 1 failures, 0 unsupported features
```

From poking around the cwltool repo, it seems that cwltool does not have an entire run of the conformance tests with `--cachedir` on CI. Is the cwltool cache meant to be fully immune to collisions?

2025-01-23 18:31 UTC, mr-c commented
> I believe the environmental variable is not part of the cache key, and since the two tests share the same tool, the later test uses the cached outputs of the first test, thus failing the environmental variable override.

Great find! Can you send a PR to cwltool to include the environement variables in the cache key calculation?

2025-02-14 15:56 UTC, adamnovak requested changes
This looks pretty good, but I found some code that I don't think is needed and some comments that could be explained a bit better.

Also, I think the new test isn't actually hooked up to ever run. We should set it to run with the scheduled integration testing runs.

2025-02-14 15:56 UTC, adamnovak commented on src/toil/cwl/cwltoil.py
> +        # Automatically bypass the file store to be compatible with cwltool caching
```suggestion
        # Automatically bypass the file store to be compatible with cwltool caching
        # Otherwise, the CWL caching code makes links to temporary local copies
        # of filestore files and caches those.
```

2025-02-14 15:56 UTC, adamnovak commented on src/toil/cwl/cwltoil.py
> +                    runtime_context.move_outputs = "move"
We're always bypassing the file store when caching now, so I don't think the change here is necessary (yet?).

2025-02-14 15:56 UTC, adamnovak commented on src/toil/test/cwl/cwlTest.py
> +        log.info("Running CWL Test Cache.")
```suggestion
        log.info("Running CWL caching test.")
```

Also won't Pytest already print what test is being run?

2025-02-14 15:56 UTC, adamnovak commented on src/toil/test/cwl/cwlTest.py
> +        from toil.cwl import cwltoil
Is there a good reason to scope the import to the test?

2025-02-14 15:56 UTC, adamnovak commented on src/toil/test/cwl/cwlTest.py
> +        # Finish the job with a correct PATH
I don't understand this comment. We don't appear to be doing anything here related to the PATH environment variable.

2025-02-14 15:56 UTC, adamnovak commented on src/toil/test/cwl/cwlTest.py
> +        # cwltool hashes certain steps into directories, ensure it exists
This could benefit from explaining why we think there should be 4 directories. Do we know that cwltool follows some rule for caching some steps but not others? Or does it actually cache all the steps, so we don't want to say "certain" and we want to say the workflow has 4 tasks?

2025-02-14 15:56 UTC, adamnovak commented on src/toil/test/cwl/cwlTest.py
> +        # Rerun the workflow to ensure there is a cache hit and that we don't rerun the workflow
```suggestion
        # Rerun the workflow to ensure there is a cache hit and that we don't rerun the tools
```

2025-02-14 15:56 UTC, adamnovak commented on src/toil/test/cwl/cwlTest.py
> +    def test_run_conformance_with_task_caching(self) -> None:
Which Gitlab job will run this? It doesn't seem to have run in CI for the PR.

2025-02-19 19:08 UTC, stxue1 commented on src/toil/cwl/cwltoil.py
> +        return 1
The cwltool logger will but we will need an error on our side

2025-02-19 19:08 UTC, stxue1 commented on src/toil/test/cwl/cwlTest.py
> +        from toil.cwl import cwltoil
I'm not too sure what the reason is, but most of the small tests in cwlTest.py rely on a local import of cwltoil.

2025-02-19 19:08 UTC, stxue1 commented on src/toil/test/cwl/cwlTest.py
> +        # Finish the job with a correct PATH
This was probably accidentally carried over when I copy pasted another test as a base

2025-02-19 19:08 UTC, stxue1 commented on src/toil/test/cwl/cwlTest.py
> +        # cwltool hashes certain steps into directories, ensure it exists
Added a comment

2025-02-19 19:08 UTC, stxue1 commented on src/toil/test/cwl/cwlTest.py
> +    def test_run_conformance_with_task_caching(self) -> None:
This should be running automatically in cwl_misc. A previous failing version of this test was seen running here: https://ucsc-ci.com/databiosphere/toil/-/jobs/87132

2025-02-19 20:35 UTC, adamnovak commented on src/toil/test/cwl/cwlTest.py
> +    def test_run_conformance_with_task_caching(self) -> None:
@stxue1 I don't think that's right. `cw_misc` looks to be running [the test for whether caching works at all](https://github.com/DataBiosphere/toil/blob/5191a94d9670fd88ce83a609af8689968f96cdc4/src/toil/test/cwl/cwlTest.py#L706-L746), whereas here we're looking at the conformance test run with caching on.

I don't think we want to run the conformance tests in `cwl_misc`, and I don't think we do. But then I think we don't run them at all. We want to run this conformance-with-caching tests along with the other scheduled conformance tests.

2025-02-20 17:58 UTC, adamnovak commented
I'm going to restart the failing test but we might need more retries on `_url_exists` that handle `urllib.error.URLError: <urlopen error [Errno -3] Temporary failure in name resolution>`.

2025-02-28 17:56 UTC, adamnovak approved these changes

2025-02-28 17:56 UTC, adamnovak commented on src/toil/options/common.py
> +    caching_help = ("Enable or disable worker level file caching for your workflow, specifying this overrides default from batch system. "
I think this is running two sentences together with a comma, which should really be `;` or `.`.

2025-02-28 17:57 UTC, merged