Add leader fallback for worker file imports
DataBiosphere/toil pull request #5189
Opened 2024-12-18 01:21 UTC by stxue1

Resolves #5135 

## Changelog Entry
To be copied to the [draft changelog](https://github.com/DataBiosphere/toil/wiki/Draft-Changelog) by merger:

 * When importing on workers, fallback to import files on the leader when file sizes are not obtainable. Related to (#5133).

## Reviewer Checklist

 * [ ] Make sure it is coming from `issues/XXXX-fix-the-thing` in the Toil repo, or from an external repo.
    * [ ] If it is coming from an external repo, make sure to pull it in for CI with:
        ```
        contrib/admin/test-pr otheruser theirbranchname issues/XXXX-fix-the-thing
        ```
    * [ ] If there is no associated issue, [create one](https://github.com/DataBiosphere/toil/issues/new).
* [ ] Read through the code changes. Make sure that it doesn't have:
    * [ ] Addition of trailing whitespace.
    * [ ] New variable or member names in `camelCase` that want to be in `snake_case`.
    * [ ] New functions without [type hints](https://docs.python.org/3/library/typing.html).
    * [ ] New functions or classes without informative docstrings.
    * [ ] Changes to semantics not reflected in the relevant docstrings.
    * [ ] New or changed command line options for Toil workflows that are not reflected in `docs/running/{cliOptions,cwl,wdl}.rst` 
    * [ ] New features without tests.
* [ ] Comment on the lines of code where problems exist with a review comment. You can shift-click the line numbers in the diff to select multiple lines.
* [ ] Finish the review with an overall description of your opinion.

## Merger Checklist

* [ ] Make sure the PR passed tests, including the Gitlab tests, for the most recent commit in its branch.
* [ ] Make sure the PR has been reviewed. If not, review it. If it has been reviewed and any requested changes seem to have been addressed, proceed.
* [ ] Merge with the Github "Squash and merge" feature.
    * [ ] If there are multiple authors' commits, add [Co-authored-by](https://github.blog/2018-01-29-commit-together-with-co-authors/) to give credit to all contributing authors.
* [ ] Copy its recommended changelog entry to the [Draft Changelog](https://github.com/DataBiosphere/toil/wiki/Draft-Changelog).
* [ ] Append the issue number in parentheses to the changelog entry.

2024-12-18 21:48 UTC, adamnovak requested changes
This looks pretty good, but I think one of the new functions is missing a docstring, and I'm not sure about the clarity of some of the variable/function names.

2024-12-18 21:48 UTC, adamnovak commented on src/toil/cwl/cwltoil.py
> +        # files with a associated filesize that are valid to be imported on workers
```suggestion
        # files with an associated filesize that are valid to be imported on workers
```

2024-12-18 21:48 UTC, adamnovak commented on src/toil/cwl/cwltoil.py
> +        valid_files_to_data = dict()
This isn't *really* mapping to file data (bits in the file), right? This is metadata consisting of file size and... something.

Maybe this should be renamed and have a comment explaining what's actually in the values? Or an inline type hint and not just auto-typing?

2024-12-18 21:48 UTC, adamnovak commented on src/toil/cwl/cwltoil.py
> +    ) -> tuple[Process, CWLObjectType]:
I think this is missing a docstring.

It also might need a better name. It sounds like it is going to e.g. convert files from DOC to PDF or something, and really it is going to fill in Toil file IDs and replace URLs with other URLs.

2025-01-08 20:37 UTC, adamnovak requested changes

2025-01-08 20:37 UTC, adamnovak commented on src/toil/cwl/cwltoil.py
> +        leader_files_to_data = dict()
I still don't think we want to name these variables `_to_data`. They don't contain file data.

We could maybe change `files_to_data`, `leader_files_to_data`, `worker_files_to_data` to instead be `metadata`, `leader_metadata`, `worker_metadata`?

2025-01-14 03:55 UTC, stxue1 commented on src/toil/cwl/cwltoil.py
> +        leader_files_to_data = dict()
I think metadata makes sense

2025-01-16 23:43 UTC, adamnovak approved these changes

2025-01-16 23:43 UTC, merged